### ISSUE TITLE
adding authentication for http monitoring?

### ISSUE THREAD

**Issue by TheRogue27** [bobbieltd/xmr-node-proxy#13]
is there any way of adding a password for the monitoring site?

**Comment by bobbieltd** [comment]
It has this password feature.
You should enable it in config.json
"accessControl": {
    "enabled": true,
    "controlFile": "accessControl.json"
  },

One of default accounts is username “test”, password “test” ( in accessControl.json )
I don’t use this feature ( it is view-only and can not cause harm to proxy ). You can try to secure by password with accessControl. Any issue, keep me in touch with details.
Thanks.

**Comment by bobbieltd** [comment]
Sorry, my mistake. I will merge from MoneroOcean upstream for http password.

**Comment by TheRogue27** [comment]
yeah, for accessing the http monitor on port 8181.
the accessControl i think it is miner related, you have to set password in the miner to be able to connect to the proxy

**Comment by bobbieltd** [comment]
Simple http authorization is implemented by https://github.com/bobbieltd/xmr-node-proxy/commit/945f9e9cc0f9e2c537e0dd86b1e20fd238ed724b (copyright by MoneroOcean)
  "httpUser": "",
  "httpPass": "",
are set in config.json

I tested it on my server. Keep me in touch if any issue.

**Comment by TheRogue27** [comment]
I must be doing something wrong, now the page loads but doesnt ask for credentials or dispaly anything. Is there suposed to fe a login form or is it like a api ip:port/user&pass kind of thing?

**Comment by bobbieltd** [comment]
Can you try it on another browser (or clear cache cookie or incognito mode) ? 
It displays nothing because I guess I still have old cache from XNP.

**Comment by bobbieltd** [comment]
For example, it should have authorization popup like this screenshot (I tested on smartphone and Windows Chrome). (Without old browser cache)

![6f27e55a-da81-4f74-b9b3-785647781fc2](https://user-images.githubusercontent.com/29669374/41575711-fa697764-73ad-11e8-8540-ab171749e989.png)

**Comment by TheRogue27** [comment]
yeap, tryed on iphone, 2 browsers and on laptop...it must be something on my side since it works for you...but cant figure out what it could be

**Comment by bobbieltd** [comment]
I guess you did “git pull” to update the codes.
Can you give me the screenshot (without IP or any delicate info) when you type xx.xx.xx.xx:8181 so I can track the issue?

**Comment by TheRogue27** [comment]
no, i just replaced the code and stop,soure&start, i'll try the git pull

**Comment by bobbieltd** [comment]
Git pull is unsuccessful because you did local commits ( proxy.js manual change ). You can run these commands (no need to put email or username, run as it is) to update proxy
cd ~/xmr-node-proxy
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git stash
git pull
npm install

**Comment by TheRogue27** [comment]
yep, works now
Cheers Bobbieltd
