### ISSUE TITLE
SuperiorCoin Use case

### ISSUE THREAD

**Issue by alebeta90** [bobbieltd/xmr-node-proxy#5]
Hello,

in the case wanting to use superiorcoin, should i use forknotev7 or cryptonightv7 ?

also im receiving this error:

Cluster master setting up 8 workers...
Worker 4265 is online
Worker 4271 is online
Worker 4272 is online
Worker 4278 is online
Worker 4284 is online
Worker 4290 is online
Worker 4301 is online
Worker 4302 is online
Master connected to pool: 10.1.108.45
Received new block template on undefined height from 10.1.108.45
buffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at new MasterBlockTemplate (/home/nodeproxy/xmr-node-proxy/lib/forknotev7.js:96:19)
    at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:719:32)
    at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:696:17)
    at Socket.socket.on.e (/home/nodeproxy/xmr-node-proxy/proxy.js:659:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

thanks in advance

**Comment by bobbieltd** [comment]
Damn ! Sorry, I don’t receive any issue notification emails for this repo by somehow.
Supercoin is cryptonightv7

**Comment by bobbieltd** [comment]
Correct, it is the same. But Snipa is lazy at maintaining the repo. That’s why MoneroOcean writes codes on his fork. For info, it’s MoneroOcean who helped Snipa to add xmr-node-proxy compatible with new Monero v7 algo.

**Comment by alebeta90** [comment]
@bobbieltd 

Good to know, I just deployed the new proxy.js with the worker stats. I just noticed that is not refreshing, I need to manually refresh it if I want to see the actual state. There is a work around to refresh such info, maybe add an interval?

All the best

**Comment by bobbieltd** [comment]
Ouff, thanks for info. Just add refresh feature (5 seconds). It's the beginning so static HTML. You can write your own page with dynamic content through API.
cd ~/xmr-node-proxy
git pull
pm2 restart proxy

Now, the page will be automatically refreshed every 5 seconds

**Comment by alebeta90** [comment]
Ok, it is excellent, I guess I can change the content and instead of showing the Password as a Name for the worker I can say to show me the wallet address right? or find a way to add like a worker name.

Thanks

**Comment by bobbieltd** [comment]
Of course, wallet address as worker name can be shown in place of password. Let me add an option to the proxy to show address in place of pass.

**Comment by bobbieltd** [comment]
Done. Address as workerID feature added.
In config.json , add   "addressWorkerID": true,
then
cd ~/xmr-node-proxy
git pull
pm2 restart proxy

Hope that helps.

**Comment by alebeta90** [comment]
Hi @bobbieltd 

it works really good :D !!!!
Case close.

thanks for everything and all the best
